version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"        # Jenkins web UI
      - "50000:50000"      # Jenkins agent communication
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Docker inside Docker (for Docker-based builds)
    environment:
      JENKINS_OPTS: "--httpPort=8080"
    restart: unless-stopped     # Restart only if stopped unexpectedly
    networks:
      - jenkins-network         # Create a custom network for better service isolation

  # Optional: add other services, like Jenkins agents or supporting services (e.g., databases)

networks:
  jenkins-network:
    driver: bridge

volumes:
  jenkins_home:
    driver: local

